# Generated by Django 5.1.15 on 2026-04-22 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes_raw', models.TextField(help_text='Raw call notes — the source document for state synthesis.')),
                ('notes_summary', models.TextField(blank=True)),
                ('llm_proposals_json', models.JSONField(blank=True, help_text='Cached tool-call output from synthesis run.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics_conducted', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='capabilities.outlet')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('availability_hours_per_week', models.PositiveSmallIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='specialists', to='capabilities.sharedtag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_committed', models.PositiveSmallIntegerField(default=0)),
                ('handover_notes', models.TextField(blank=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='capabilities.outlet')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='diagnostics.specialist')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('funding_notes', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='sponsors', to='capabilities.sharedtag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_day', models.PositiveSmallIntegerField(choices=[(30, '30 days'), (60, '60 days'), (90, '90 days')])),
                ('scheduled_for', models.DateField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('behavioural_answers', models.JSONField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='capabilities.outlet')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'unique_together': {('outlet', 'milestone_day')},
            },
        ),
    ]
