# Generated by Django 5.1.15 on 2026-04-22 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('baseline', models.BooleanField(default=False, help_text='Expected of every outlet by exit.')),
                ('template_able', models.BooleanField(default=False, help_text='Artefact is reusable across outlets.')),
                ('phase', models.CharField(choices=[('advisory', 'Advisory'), ('activation', 'Activation'), ('resources', 'Resources')], default='advisory', max_length=16)),
                ('assessment_method', models.CharField(choices=[('interview', 'Interview'), ('survey', 'Survey'), ('file_transfer', 'File transfer'), ('automated', 'Automated')], default='interview', max_length=16)),
                ('cross_desk_dep', models.CharField(blank=True, help_text="Free-text pointer to another desk's capability when progress here is gated elsewhere.", max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['cluster', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(choices=[('audience_development', 'Audience Development')], default='audience_development', max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['desk', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cohort', models.CharField(blank=True, help_text='Wave / cohort label.', max_length=64)),
                ('enrolment_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('region', 'Region'), ('language', 'Language'), ('format', 'Format'), ('topic', 'Topic')], max_length=16)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['dimension', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Aware'), (2, 'Practising'), (3, 'Embedded'), (4, 'Data-champion-led')], default=0)),
                ('evidence_excerpt', models.TextField(help_text='Quoted evidence from the diagnostic — required, no empty rows.')),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('llm_proposed', models.BooleanField(default=False)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states_accepted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='capabilities.capabilityitem')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
            },
        ),
    ]
