# Generated by Django 5.1.15 on 2026-04-22 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capabilities', '0001_initial'),
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilitystate',
            name='source_diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_changes', to='diagnostics.diagnostic'),
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('desk', 'name')},
        ),
        migrations.AddField(
            model_name='capabilityitem',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='capabilities.cluster'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='data_champion',
            field=models.ForeignKey(blank=True, help_text='Outlet-side person carrying practice forward post-handover (Bus Factor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champions_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capabilitystate',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='capabilities.outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedtag',
            unique_together={('dimension', 'value')},
        ),
        migrations.AddField(
            model_name='outlet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='outlets', to='capabilities.sharedtag'),
        ),
        migrations.AlterUniqueTogether(
            name='capabilityitem',
            unique_together={('cluster', 'name')},
        ),
        migrations.AddIndex(
            model_name='capabilitystate',
            index=models.Index(fields=['outlet', 'item', '-set_at'], name='capabilitie_outlet__a2a3b3_idx'),
        ),
    ]
