# Generated by Django 5.1.15 on 2026-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilitystate',
            name='led_by_champion',
            field=models.BooleanField(default=False, help_text='This capability is currently sustained by an outlet-side data champion (Bus Factor).'),
        ),
        migrations.AlterField(
            model_name='capabilitystate',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Aware'), (2, 'Practising'), (3, 'Embedded')], default=0),
        ),
    ]
