# Generated by Django 5.1.15 on 2026-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0003_capabilitystate_led_by_champion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='mismatch_flag_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='mismatch_flag_json',
            field=models.JSONField(blank=True, help_text='Cached output of the LLM mismatch flagger: headline, flags, bus_factor_risk.', null=True),
        ),
    ]
